### ISSUE TITLE
Is there something wrong with my usage?

### ISSUE THREAD

**Issue by HLeonHong** [chaoyangnz/scs-extract#2]
E:\Games\ETS\locale
locale.scs（1.50）

I launch it using cmd.
E:\Games\ETS\locale>scs-extract E:\Games\ETS\locale\locale.scs E:\Games\ETS\locale
E:\Games\ETS\locale>scs-extract locale.scs E:\Games\ETS\locale

`E:\Games\ETS\locale>scs-extract E:\Games\ETS\locale\locale.scs E:\Games\ETS\locale
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x10aa959]

goroutine 1 [running]:
io.ReadAll({0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:701 +0xd9
github.com/chaoyangnz/scs-extract/scs.NewHashfs({0xc000010140, 0x1e})
        E:/ets2/scs-extract-master/scs/hashfs.go:65 +0x307
main.newImpl({0xc000010140, 0x1e}, {0xc000012180, 0x13}, 0x0, {0x13e3870, 0x0, 0x0})
        E:/ets2/scs-extract-master/main.go:59 +0xbc
main.main.func1(0x1?)
        E:/ets2/scs-extract-master/main.go:48 +0x6a
github.com/urfave/cli.HandleAction({0x11bb960?, 0xc0000080d8?}, 0xc00016c000?)
        C:/Users/chao.yang/go/pkg/mod/github.com/urfave/cli@v1.22.13/app.go:524 +0x50
github.com/urfave/cli.(*App).Run(0xc00016c000, {0xc000024080, 0x3, 0x4})
        C:/Users/chao.yang/go/pkg/mod/github.com/urfave/cli@v1.22.13/app.go:286 +0x7db
main.main()
        E:/ets2/scs-extract-master/main.go:52 +0x408

E:\Games\ETS\locale>`

`E:\Games\ETS\locale>scs-extract locale.scs E:\Games\ETS\locale
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x10aa959]

goroutine 1 [running]:
io.ReadAll({0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:701 +0xd9
github.com/chaoyangnz/scs-extract/scs.NewHashfs({0xc00000e100, 0xa})
        E:/ets2/scs-extract-master/scs/hashfs.go:65 +0x307
main.newImpl({0xc00000e100, 0xa}, {0xc000012180, 0x13}, 0x0, {0x13e3870, 0x0, 0x0})
        E:/ets2/scs-extract-master/main.go:59 +0xbc
main.main.func1(0x1?)
        E:/ets2/scs-extract-master/main.go:48 +0x6a
github.com/urfave/cli.HandleAction({0x11bb960?, 0xc0000080d8?}, 0xc00016a000?)
        C:/Users/chao.yang/go/pkg/mod/github.com/urfave/cli@v1.22.13/app.go:524 +0x50
github.com/urfave/cli.(*App).Run(0xc00016a000, {0xc000024080, 0x3, 0x4})
        C:/Users/chao.yang/go/pkg/mod/github.com/urfave/cli@v1.22.13/app.go:286 +0x7db
main.main()
        E:/ets2/scs-extract-master/main.go:52 +0x408

E:\Games\ETS\locale>`

**Comment by chaoyangnz** [comment]
Sorry I am not sure why. from the error message, it seems an error occurred when decompressing a directory in the hashfs.

Have you tried the community extract tool?

**Comment by HLeonHong** [comment]
https://modding.scssoft.com/wiki/Documentation/Tools/Game_Archive_Extractor

This one ?

Is this right ?
![image](https://github.com/chaoyangnz/scs-extract/assets/44226142/ba739ee8-2402-4821-8d1a-0a5b3629f101)
